# Generated by Django 3.0.4 on 2020-03-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=336.6666666666667, max_length=200),
            preserve_default=False,
        ),
    ]
